language: ruby

rvm:
  2.1

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

sudo: required

before_install:
  - sudo mysql -e 'CREATE DATABASE anonymizer;'

script:
  - cp config/env/sample.yml config/env/development.yml
  - bundle exec rubocop
  - bundle exec rspec spec/unit
  - bundle exec rspec spec/system
