version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: anonymizer
      MYSQL_USER: anonymizer
      MYSQL_PASSWORD: anonymizer
      MYSQL_ROOT_PASSWORD: anonymizer
    command: --default-authentication-plugin=mysql_native_password
