version: '3'
services:
  ruby:
    image: ruby:2.3
    build:
      context: ../../../
      dockerfile: dev/docker/ruby2.3/anonymizer/Dockerfile
    volumes:
      - "../../../:/usr/src/anonymizer"
    depends_on:
      - mysql
    command: ['bash', '-c', 'sleep 60000']
  mysql:
    image: mysql:8
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: anonymizer
      MYSQL_USER: anonymizer
      MYSQL_PASSWORD: anonymizer
      MYSQL_ROOT_PASSWORD: anonymizer
    command: --default-authentication-plugin=mysql_native_password
  postfix:
    image: catatnight/postfix
    ports:
      - 25
    environment:
      maildomain: divante.pl
      smtp_user: anonymizer:password
